language: php

php: [5.5]

matrix:
    fast_finish: true

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - php ./bldr.phar install

script:
    - php ./bldr.phar test
    - php ./bldr.phar run secure
