language: php

php: [5.5]

matrix:
    fast_finish: true

sudo: false

#cache:
#    directories:
#        - $HOME/.composer/cache

before_install:
    - curl -sS http://bldr.io/installer | php
    - php ./bldr.phar install

script:
    - php ./bldr.phar test
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php ./bldr.phar run secure; fi;'
