language: php

php: [5.4, 5.5, hhvm-nightly]

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm-nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - curl -sS http://bldr.io/installer | php
    - php ./bldr.phar install

script:
    - php ./bldr.phar test
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php ./bldr.phar run secure; fi;'
