services:
    qandidate.repository.game:
        class: Qandidate\GameRepository
        arguments:
            - @qandidate.driver.sql

    qandidate.driver.sql:
        class: Qandidate\SqlStorage
        arguments:
            - '%database_name%'
            - '%database_username%'
            - '%database_password%'
