services:
    qandidate.repository.game:
        class: Qandidate\GameRepository
        arguments:
            - @qandidate.driver.sqlite3

    qandidate.driver.sqlite3:
        class: Qandidate\SqliteStorage
